import io
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

# --------------------------------------------------
# PDF REPORT GENERATOR
# --------------------------------------------------


def generate_report(health_score, status, priority, defects, recommendation):
    """
    Generates SteelVision AI inspection PDF report.

    Returns:
        PDF bytes
    """

    buffer = io.BytesIO()

    document = SimpleDocTemplate(buffer, pagesize=letter)

    styles = getSampleStyleSheet()

    content = []

    # Title

    content.append(
        Paragraph("SteelVision AI - Machine Inspection Report", styles["Title"])
    )

    content.append(Spacer(1, 20))

    # Date

    content.append(
        Paragraph(
            f"""
            Inspection Date:
            {datetime.now().strftime("%d-%m-%Y %H:%M")}
            """,
            styles["Normal"],
        )
    )

    content.append(Spacer(1, 12))

    # Machine Health

    content.append(
        Paragraph(
            f"""
            Machine Health Score:
            {health_score}%
            """,
            styles["Normal"],
        )
    )

    content.append(
        Paragraph(
            f"""
            Machine Status:
            {status}
            """,
            styles["Normal"],
        )
    )

    content.append(
        Paragraph(
            f"""
            Maintenance Priority:
            {priority}
            """,
            styles["Normal"],
        )
    )

    content.append(Spacer(1, 20))

    # Defects

    content.append(Paragraph("Detected Defects:", styles["Heading2"]))

    if defects:

        for defect in defects:

            text = f"""
                {defect['name']}
                -
                Confidence:
                {round(defect['confidence']*100,2)}%
                """

            content.append(Paragraph(text, styles["Normal"]))

    else:

        content.append(Paragraph("No defects detected.", styles["Normal"]))

    content.append(Spacer(1, 20))

    # Recommendation

    content.append(Paragraph("AI Maintenance Recommendation:", styles["Heading2"]))

    content.append(Paragraph(recommendation.replace("\n", "<br/>"), styles["Normal"]))

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            """
            Generated by SteelVision AI
            Industry 4.0 Edge AI Inspection Platform
            """,
            styles["Italic"],
        )
    )

    document.build(content)

    buffer.seek(0)

    return buffer
